create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  attending boolean not null,
  guest_count integer not null default 1 check (guest_count >= 1 and guest_count <= 10),
  language text not null default 'mk' check (language in ('mk', 'hr')),
  transport text check (transport in ('organized', 'own')),
  additional_guests jsonb not null default '[]'::jsonb,
  dietary_notes text,
  message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rsvps
  add column if not exists language text not null default 'mk' check (language in ('mk', 'hr'));

alter table public.rsvps
  add column if not exists transport text check (transport in ('organized', 'own'));

alter table public.rsvps
  add column if not exists additional_guests jsonb not null default '[]'::jsonb;

create index if not exists rsvps_language_idx on public.rsvps (language);
create index if not exists rsvps_transport_idx on public.rsvps (transport);
create index if not exists rsvps_created_at_idx on public.rsvps (created_at desc);

update public.rsvps
set language = case
  when email like 'hr-%' then 'hr'
  else 'mk'
end
where language is null or language = 'mk';

update public.rsvps
set transport = case
  when lower(coalesce(dietary_notes, '')) like '%сопствен%'
    or lower(coalesce(dietary_notes, '')) like '%vlastiti%'
    or lower(coalesce(dietary_notes, '')) like '%own%' then 'own'
  when lower(coalesce(dietary_notes, '')) like '%организиран%'
    or lower(coalesce(dietary_notes, '')) like '%organiziran%'
    or lower(coalesce(dietary_notes, '')) like '%organized%' then 'organized'
  else transport
end
where transport is null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_rsvps_updated_at on public.rsvps;
create trigger set_rsvps_updated_at
before update on public.rsvps
for each row
execute function public.set_updated_at();

alter table public.rsvps enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on public.rsvps to anon;
grant select, insert, update, delete on public.rsvps to authenticated;
grant usage, select on sequence public.rsvps_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit RSVP" on public.rsvps;
create policy "Anyone can submit RSVP"
on public.rsvps
for insert
to anon
with check (true);

drop policy if exists "Admins can insert RSVP" on public.rsvps;
create policy "Admins can insert RSVP"
on public.rsvps
for insert
to authenticated
with check (true);

drop policy if exists "Anyone can read RSVP for insert response" on public.rsvps;
create policy "Anyone can read RSVP for insert response"
on public.rsvps
for select
to anon
using (true);

drop policy if exists "Admins can read RSVP" on public.rsvps;
create policy "Admins can read RSVP"
on public.rsvps
for select
to authenticated
using (true);

drop policy if exists "Admins can update RSVP" on public.rsvps;
create policy "Admins can update RSVP"
on public.rsvps
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Admins can delete RSVP" on public.rsvps;
create policy "Admins can delete RSVP"
on public.rsvps
for delete
to authenticated
using (true);
